# Generated by Django 5.2.8 on 2025-11-13 06:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignbudget',
            options={'verbose_name_plural': 'Campaign budgets'},
        ),
        migrations.AlterModelOptions(
            name='campaignusagedaily',
            options={'verbose_name_plural': 'Campaign daily usage'},
        ),
        migrations.AlterField(
            model_name='campaignusagedaily',
            name='usage_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='campaigns_c_is_acti_7a198a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='campaigns_c_start_d_996cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignusagedaily',
            index=models.Index(fields=['campaign', 'customer', 'usage_date'], name='campaigns_c_campaig_f5d28d_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='campaign_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'PERCENT'), ('discount_value__gte', Decimal('0.00')), ('discount_value__lte', Decimal('100.00'))), models.Q(('discount_type', 'FLAT'), ('discount_value__gte', Decimal('0.00'))), _connector='OR'), name='campaign_discount_value_valid'),
        ),
    ]
